version: '3'
services:
  accounts:
    image: "postgres:11"
    container_name: "db"
    # environment:
    #   - POSTGRES_USER=${DB_USER}  
    #   - POSTGRES_PASSWORD=${DB_PASSWORD}
    #   - POSTGRES_DB=${DB_NAME}
    #   - DATABASE_HOST=${DB_HOST} 
    networks: 
      - blogging
    ports:
      - "5432:5432"
    volumes:
      - accounts_data:/var/lib/postgresql/data
  graphql:
    build: .
    container_name: graphql
    ports:
      - 8080:8080
    restart: on-failure
    networks: 
      - blogging
    depends_on:
      - accounts
volumes:
  accounts_data:
networks:
  blogging:
    driver: bridge