// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Todo struct {
	ID      string `json:"id"`
	Text    string `json:"text"`
	Done    bool   `json:"done"`
	Comment string `json:"comment"`
	User    *User  `json:"user"`
}

type User struct {
	ID        string `json:"id"`
	CreatedAt int    `json:"createdAt"`
	UpdatedAt int    `json:"updatedAt"`
	DeletedAt *int   `json:"deletedAt"`
	Username  string `json:"username"`
	Password  string `json:"password"`
	Email     string `json:"email"`
	Active    bool   `json:"active"`
}
