// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: servers/blogging/proto/blogging.proto

package go_blogging_graphql

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Blogging service

type BloggingService interface {
	AddPost(ctx context.Context, in *AddPostRequest, opts ...client.CallOption) (*AddPostResponse, error)
}

type bloggingService struct {
	c    client.Client
	name string
}

func NewBloggingService(name string, c client.Client) BloggingService {
	return &bloggingService{
		c:    c,
		name: name,
	}
}

func (c *bloggingService) AddPost(ctx context.Context, in *AddPostRequest, opts ...client.CallOption) (*AddPostResponse, error) {
	req := c.c.NewRequest(c.name, "Blogging.AddPost", in)
	out := new(AddPostResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Blogging service

type BloggingHandler interface {
	AddPost(context.Context, *AddPostRequest, *AddPostResponse) error
}

func RegisterBloggingHandler(s server.Server, hdlr BloggingHandler, opts ...server.HandlerOption) error {
	type blogging interface {
		AddPost(ctx context.Context, in *AddPostRequest, out *AddPostResponse) error
	}
	type Blogging struct {
		blogging
	}
	h := &bloggingHandler{hdlr}
	return s.Handle(s.NewHandler(&Blogging{h}, opts...))
}

type bloggingHandler struct {
	BloggingHandler
}

func (h *bloggingHandler) AddPost(ctx context.Context, in *AddPostRequest, out *AddPostResponse) error {
	return h.BloggingHandler.AddPost(ctx, in, out)
}
